# Use an official TensorFlow runtime as a parent image
FROM tensorflow/tensorflow:2.6.0

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install --upgrade pip setuptools wheel
RUN pip install flask
RUN pip install numpy
RUN pip install opencv-contrib-python-headless==4.1.2.30
#RUN pip install opencv-python-headless == 4.1.2.30
RUN pip install matplotlib

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]
